# Generated by Django 5.1.7 on 2025-04-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_affirmation_affirmationcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaxationTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
