# Generated by Django 5.1.7 on 2025-04-14 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_relaxationtechnique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipcomment',
            old_name='commented_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tipcomment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='stresstip',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TipLike',
        ),
    ]
