# Generated by Django 5.1.7 on 2025-04-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_focussession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FocusSession',
        ),
    ]
